### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by scottpageindysoft** [Azure/react-azure-maps#105]
Please upgrade to React 17.

Also, is this project still active?

**Comment by drjonnicholson** [comment]
Also interested in this - is there an ETA on update to r17?

**Comment by dubiety** [comment]
Hi @scottpageindysoft  and @drjonnicholson , sorry for the late reply. We will support React 17 soon. Will keep you posted. Thank you for filing the issue to us.

**Comment by dubiety** [comment]
Hi @scottpageindysoft @drjonnicholson , we now support r17 in v0.4.2. Please create new issue if there is any other problem. Thank you very much.
