### ISSUE TITLE
[Question] react-azure-maps and azure-maps-control lazy loading

### ISSUE THREAD

**Issue by SridharKundojjala** [Azure/react-azure-maps#136]
We are trying to do code splitting and observed that react-azure-maps and azure-maps-control take a significant amount of space in bundle. 
When trying to use react.lazy to lazy load the required portions of the components it is giving below errors in typescript for compilation.
Are there any samples to do the code lazy loading of the component?

Type 'Promise<{ default: never; } | { default: typeof AuthenticationType; }>' is not assignable to type 'Promise<{ default: ComponentType<any>; }>'.
  Type '{ default: never; } | { default: typeof AuthenticationType; }' is not assignable to type '{ default: ComponentType<any>; }'.
    Type '{ default: typeof atlas.AuthenticationType; }' is not assignable to type '{ default: ComponentType<any>; }'.
      Types of property 'default' are incompatible.
        Type 'typeof AuthenticationType' is not assignable to type 'ComponentType<any>'.ts(2322)
index.d.ts(869, 18): The expected type comes from the return type of this signature.

**Comment by yulinscottkang** [comment]
@SridharKundojjala, I haven't tried react.lazy but I have a demo app that uses next/dynamic to lazy load the Map component. https://github.com/yulinscottkang/nextjs-azure-maps
