### ISSUE TITLE
Unable to add traffic Options in AzureMap

### ISSUE THREAD

**Issue by Vedantthakkar** [Azure/react-azure-maps#141]
Hi,

I am trying to add traffic options into the azure Map, but it is giving me following error:

> The source 'incidents-source' could not be added to the map because the map is not ready. Please use a ready event listener to guarantee the map is ready before adding a source to it.

Using the below basic Setup code:
```javascript
<AzureMapsProvider>
  <AzureMap  options={option} trafficOptions={{ flow: 'absolute', incidents: true }} />
</AzureMapsProvider>

```
Please help!

**Comment by yulinscottkang** [comment]
hi @Vedantthakkar, I tried the following code and didn't see the error mentioned. However, there's another error and was able to mitigate it by setting `incidents: false`

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x')


```js
import { AzureMap, AzureMapsProvider } from "react-azure-maps";

const option = {
  zoom: 12,
  center: [-122.335, 47.62],
  authOptions: {
    authType: "subscriptionKey",
    subscriptionKey: ""
  }
};

export default function App() {
  return (
    <AzureMapsProvider>
      <div style={{ height: "300px" }}>
        <AzureMap
          options={option}
          trafficOptions={{ flow: "absolute", incidents: false }}
        />
      </div>
    </AzureMapsProvider>
  );
}

```

**Comment by Vedantthakkar** [comment]
Hi @yulinscottkang, Thanks for looking into the issue. Although you are not able to see the error message, I am getting error while using the same code. I tried with different options. Here is one more error message I am getting while using the same code with flow as "relative" and incidents as false 

> Traffic flow could not be added to the map because the map is not ready.

Even if it woks with incidents as false, we need the incidents to show up on the map.  Can you help me find any work around for this issue? Thanks

**Comment by yulinscottkang** [comment]
Does the map show up properly without using the `trafficOptions` ? 
If it does, perhaps you can also try using `mapRef.setTraffic(...)` once the map is fully loaded. 

```js
import React, { useContext } from "react";
import { AzureMap, AzureMapsProvider, AzureMapsContext } from "react-azure-maps";

const option = {
  zoom: 12,
  center: [-122.335, 47.62],
  authOptions: {
    authType: "subscriptionKey",
    subscriptionKey: ""
  }
};

const Controller = () => {
  const { mapRef, isMapReady } = useContext(AzureMapsContext);
  if (mapRef && isMapReady) {
    mapRef.setTraffic({ flow: "relative", incidents: false });
  }
  return null;
};

export default function App() {
  return (
    <AzureMapsProvider>
      <div style={{ height: "300px" }}>
        <Controller />
        <AzureMap options={option} />
      </div>
    </AzureMapsProvider>
  );
}
```

**Comment by Vedantthakkar** [comment]
Yes, the map shows up properly without using the `trafficOptions`. 
The above workaround worked for me. However, since the AzureMap component already provides option to pass traffic options and it is giving errors while doing so, can this be considered a bug? And if so, can we solve this? This will eliminate the need for 1 extra component to show traffic. I can also help and solve this issue.

**Comment by yulinscottkang** [comment]
hi @Vedantthakkar, I wasn't able to reproduce the issue you mentioned. I suspect it might be related to how the map component is mounted in the first place. It would be great if you can provide a small and complete project to demonstrate the problem (for example, using https://codesandbox.io/). Thanks!
