### ISSUE TITLE
Draggable marker location resets after zoom out on Map

### ISSUE THREAD

**Issue by joebeernink** [Azure/react-azure-maps#142]
I have a marker where draggable = true;

            // Create an HtmlMarker.
            const marker = new HtmlMarker({
                draggable: props.isDraggable
            });

I drag the marker on the map and I get the dragend event and process it:

                    mapRef.events.add('dragend', marker, (e: any) => {
                        var pos = e.target.options.position;
                        handleLocationChange(pos);
                    });

Now if I zoom out on the map, the marker sometimes jumps back to the original location. No dragend event is captured, and handleLocationChange is never fired. This doesn't always happen. Sometimes depends on how much you zoom out. I don't see an issue if I just drag the map around and send the pin out of frame. It stays where it should be.

Perhaps related... I notice that after I drag the pin once, the handleLocationChange event fires once. When I drag it a second time, it fires twice. Three times four, etc... I've verified that I am only adding the markerLayer to the mapRef once, and only adding the point to the datasource once.

Am using 
"react-azure-maps": "^0.4.4",
"azure-maps-control": "^2.0.32",

Also noticed that when marker is draggable, the click event on the mapref is never fired.

``` typescript

    useEffect(() => {
        if (mapRef && props.isEventDataLoaded && props.isMapKeyLoaded && !isDataSourceLoaded && isMapReady) {

            // Simple Camera options modification
            mapRef.setCamera({ center: props.center, zoom: MapStore.defaultUserLocationZoom });

            var dataSourceRef = new source.DataSource("mainDataSource", { cluster: true });

            mapRef.sources.add(dataSourceRef);
            setIsDataSourceLoaded(true);

            // Create a reusable popup.
            const popup = new Popup({
                pixelOffset: [0, -20],
                closeButton: false
            });

            // Create an HtmlMarker.
            const marker = new HtmlMarker({
                draggable: props.isDraggable
            });

            // Create a HTML marker layer for rendering data points.
            var markerLayer = new HtmlMarkerLayer(dataSourceRef, "marker1", {
                markerCallback: (id: any, position: data.Position, properties: any) => {

                    marker.setOptions({
                        position: position
                    });

                    mapRef.events.add('mouseover', marker, (event: any) => {
                        const marker = event.target as HtmlMarker & { properties: any };
                        const date = new Date(marker.properties.eventDate).toLocaleDateString([], { month: "long", day: "2-digit", year: "numeric" });
                        const time = new Date(marker.properties.eventDate).toLocaleTimeString([], { timeZoneName: 'short' });
                        const content = marker.properties.cluster
                            ? `Cluster of ${marker.properties.point_count_abbreviated} markers`
                            : `<div className="map-popup-container" style="padding:0.5rem;">
                                <h5 style="font-weight: 500; font-size: 18px; margin-top: 0.5rem;">${marker.properties.name}</h5>
                                <div><span className="font-weight-bold">Event Date: </span><span>${date}</span></div>
                                <div><span className="font-weight-bold">Time: </span><span>${time}</span></div>

                                <div>
                            </div>`;
                        popup.setOptions({
                            content: content,
                            position: marker.getOptions().position
                        });

                        // Open the popup.
                        if (mapRef) {
                            popup.open(mapRef);
                        }
                    });

                    mapRef.events.add('dragend', marker, (e: any) => {
                        var pos = e.target.options.position;
                        handleLocationChange(pos);
                    });

                    //mapRef.events.add('click', marker, (e: any) => {
                    //    var pos = e.target.options.position;
                    //    handleLocationChange(pos);
                    //});

                    mapRef.events.add('mouseout', marker, () => popup.close());

                    return marker
                }
            });

            // Add marker layer to the map.
            mapRef.layers.add(markerLayer);

            var position = new data.Point(new data.Position(props.longitude, props.latitude));

            var featureProperties = ({
                name: props.eventName,
                eventDate: props.eventDate,
            });

            dataSourceRef.add(new data.Feature(position, featureProperties));
        }
    }, [mapRef,
        props.center,
        props.isEventDataLoaded,
        props.isMapKeyLoaded,
        props.currentUser,
        props.isUserLoaded,
        props.eventName,
        props.eventDate,
        props.longitude,
        props.latitude,
        isDataSourceLoaded,
        props.isDraggable,
        // eslint-disable-next-line
        handleLocationChange,
        isMapReady,
        isPrevLoaded]);

    useEffect(() => {
        if (mapRef && props.isEventDataLoaded && props.isMapKeyLoaded && isDataSourceLoaded && isMapReady && !isPrevLoaded) {
            var dsr = mapRef.sources.getById("mainDataSource") as source.DataSource;
            var feature = dsr.getShapes()[0];

            var position = new data.Position(props.longitude, props.latitude);

            // if the value is (0,0) this is a default. Use the user's position instead if available
            if (props.latitude === 0 && props.longitude === 0) {
                position = props.center;
            }

            feature.setCoordinates(position);

            // Simple Camera options modification
            mapRef.setCamera({ center: position, zoom: MapStore.defaultUserLocationZoom });
            setIsPrevLoaded(true);
        }
    }, [mapRef,
        props.center,
        props.isEventDataLoaded,
        props.isMapKeyLoaded,
        props.longitude,
        props.latitude,
        isDataSourceLoaded,
        isMapReady]);

    // eslint-disable-next-line
    function handleLocationChange(e: any) {
        props.onLocationChange(e);
    }

```

**Comment by yulinscottkang** [comment]
hi @joebeernink, I'm trying to reproduce and figure out if this issue is caused by azure-maps-control, react-azure-maps, or the custom `HtmlMarkerLayer` that is used in the example code. 

Here're some questions that might be helpful:

1. Are you able to reproduce the issue with plain azure-maps-control (without using react-azure-maps)? For example using one of the samples from this page: https://learn.microsoft.com/en-us/azure/azure-maps/map-add-custom-html#draggable-html-markers.

2. Is `HtmlMarkerLayer._updateMarkers()` being called when the issue occurs? If yes, do the markers update correctly with respect to the current zoom level?  

3. If you're rendering the marker for a single feature, you might want to try using `AzureMapHtmlMarker` instead of `HtmlMarkerLayer`.

**Comment by joebeernink** [comment]
Hi @yulinscottkang 

I am not able to repro the issue on the plain azure maps control, so I'm betting this is an internal issue with the HtmlMarkerLayer

I had forgotten that we had taken a copy of the code from the HtmlMarkerLayer (https://github.com/Azure-Samples/azure-maps-html-marker-layer) a year or so ago to fix some issues locally. Not sure how out of date we are now with the code that is in this repo... @ambientlight and I had worked on this, and went back and forth quite a but to get things working properly before the Azure Maps Team officially took this over. Now wondering if I need to rip the HtmlMarkerLayer out all together and try with the new AzureMapsLayer?

Should it "just work" now? Or will I still need the code from https://github.com/Azure-Samples/azure-maps-html-marker-layer?

**Comment by yulinscottkang** [comment]
hi @joebeernink, thank you for the context!

I noticed that in your example, you're returning the same instance of `HtmlMarker` in your `markerCallback()`. Whereas in the [azure-maps-html-marker-layer](https://github.com/Azure-Samples/azure-maps-html-marker-layer) examples, a new instance of `HtmlMarker` is created and returned for each call to the `markerCallback()` callback. Maybe you can try the same thing and see if that solves the problem? It should also solve the problem that `handleLocationChange` was called multiple times after multiple drags in your example.

And if you don't need the clustering feature from `HtmlMarkerLayer` and just want to render a `HtmlMarker` for a single point, you can also try using [AzureMapHtmlMarker](https://github.com/Azure/react-azure-maps-playground/blob/94458ab2605170a96cd37757ff668286f93bfe84/src/examples/MarkersExample/MarkersExample.tsx#L69) from react-azure-maps. It's much simpler and also supports the `draggable` option.

**Comment by joebeernink** [comment]
Thanks @yulinscottkang. Had to make 2 changes.  
1. Move the creation of the html marker inside the markerCallback,
2. Clear the datasource in the marker callback (or I end up with a new marker every time the drag stops). This approach works fine when there is only supposed to be one draggable marker, but I would imagine that this will cause issues if there are multiple markers.

For now, this problem is resolved. Thanks for the help!
