### ISSUE TITLE
AzureMapHtmlMarker doesn't include styles generated by styled components 

### ISSUE THREAD

**Issue by JLittner** [Azure/react-azure-maps#146]
Hello guys, 
I'm not able to see in browser any styles generated by MUI styled() utility when I'm passing styled component as a markerContent prop into an AzureMapHtmlMarker.

`
const StyledIcon = styled(Icon)(({ theme }) => ({
  fontSize: 25,
}));

const StyledText = styled('span')({
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%,-50%)',
});

...

const markerContent = (
  <div>
    <StyledIcon  width={40} />
    <StyledText >{text}</StyledText>
  </div>
);

<AzureMapHtmlMarker
  key={`some-generated-key`}
  options={{
    position: [longitude, latitude],
  }}
  markerContent={markerContent}
/>
`
Will be styled components supported in a future or is there any pretty workaround?
Thanks in advance!

**Comment by yulinscottkang** [comment]
hi @JLittner, there's a (not-so-pretty) workaround by rendering a hidden copy of your styled components outside of the `<AzureMapsProvider>` container, so that the css can be generated on the page. For example, 

![image](https://user-images.githubusercontent.com/953349/220852537-c73df77c-4532-4481-85a0-f60d35fb31a6.png)

```js
import * as React from "react";
import * as ReactDOM from "react-dom/client";
import { Button, styled } from "@mui/material";
import {
  AzureMap,
  AzureMapsProvider,
  AzureMapHtmlMarker
} from "react-azure-maps";
import { data } from "azure-maps-control";

const option = {
  zoom: 12,
  center: [-122.335, 47.62],
  authOptions: {
    authType: "subscriptionKey",
    subscriptionKey: "<subscriptionKey>"
  }
};

const position = new data.Position(-122.335, 47.62);

const StyledButton = styled(Button)(() => ({
  fontSize: 25
}));

function MyApp() {
  return (
    <>
      <AzureMapsProvider>
        <div style={{ height: "300px" }}>
          <AzureMap options={option}>
            <AzureMapHtmlMarker
              key="1"
              markerContent={
                <div className="pulseIcon">
                  <StyledButton variant="contained">Hello World</StyledButton>
                </div>
              }
              options={{ position }}
            />
          </AzureMap>
        </div>
      </AzureMapsProvider>
      <StyledButton style={{ display: "none" }} variant="contained"></StyledButton>
    </>
  );
}

ReactDOM.createRoot(document.querySelector("#app")).render(
  <React.StrictMode>
    <MyApp />
  </React.StrictMode>
);
```

**Comment by JLittner** [comment]
Hi, 
Thanks for fast answer.

I tried this approach but it didn't work for me.  It could be because I had the styled component separated in another component with additional logic and this I tried to render outside of '<AzureMapsProvider>' and than in the map.

I ended up with css classes and definition of styles for them in the parent component.

'
import * as React from "react";
import * as ReactDOM from "react-dom/client";
import { Button, styled } from "@mui/material";
import {
  AzureMap,
  AzureMapsProvider,
  AzureMapHtmlMarker
} from "react-azure-maps";
import { data } from "azure-maps-control";

const option = {
  zoom: 12,
  center: [-122.335, 47.62],
  authOptions: {
    authType: "subscriptionKey",
    subscriptionKey: "<subscriptionKey>"
  }
};

const position = new data.Position(-122.335, 47.62);

const AzureMapContainer = styled('div')(() => ({
    height: '100%',
    width: '100%',
    overflow: 'hidden',
  
    // Styled button
    '& .styled-button': {
        fontSize: 25
    },
}));

function MyApp() {
  return (
    <AzureMapContainer>
      <AzureMapsProvider>
        <div style={{ height: "300px" }}>
          <AzureMap options={option}>
            <AzureMapHtmlMarker
              key="1"
              markerContent={
                  <Button variant="contained" className="styled-button">Hello World</Button>
              }
              options={{ position }}
            />
          </AzureMap>
        </div>
      </AzureMapsProvider>
      <StyledButton style={{ display: "none" }} variant="contained"></StyledButton>
    </AzureMapContainer>
  );
}

ReactDOM.createRoot(document.querySelector("#app")).render(
  <React.StrictMode>
    <MyApp />
  </React.StrictMode>
);
'

Thank you again for your support.
