### ISSUE TITLE
Doubled canvas and container

### ISSUE THREAD

**Issue by xde** [Azure/react-azure-maps#160]
On latest version 0.4.7 when inspecting rendered elements I have noticed, that inside **"mapbox-map altas-map"** container,
there are **two** divs **"mapboxgl-canvas-container .... atlas-map-canvas-container"**, both with **"canvas"** inside.
So if we remove one div or canvas, there is another map underneath...

This doesn't affect visibility of map but I guess performance is not so good?

Haven't notice the issue, until I added option "**renderWorldCopies: false**" and when zooming out all the way, **instead of blank screen on sides, there is another map underneath**...
You can interact with that one also :D

I don't think this is my issue as after adding src/key.ts (export const key="...") here:
https://codesandbox.io/s/azure-maps-playground-2zscu3
issue is also visible.

In **mapbox** there isn't such problem with renderWorldCopies to false:
https://docs.mapbox.com/mapbox-gl-js/example/render-world-copies/

In **Azure map samples** same no issue with "Render world copies:" unchecked
https://samples.azuremaps.com/map/map-style-options

**Comment by yulinscottkang** [comment]
Thanks for reporting the issue! The issue occurs when React 18's strict mode is enabled in development. A fix will be released soon.

**Comment by xde** [comment]
Correct, React 18.2 with StrictMode on, dev mode. Thanks for fix :)

**Comment by yulinscottkang** [comment]
Fixed in https://github.com/Azure/react-azure-maps/releases/tag/0.4.8
