### ISSUE TITLE
Layer events when using MapRef

### ISSUE THREAD

**Issue by Morti** [Azure/react-azure-maps#163]
Hi, I would like to revisit the problem raised in issue #134 

The issue still seems to remain that when you add an event to a layer when using MapRef the event isn't triggered. And the suggestion in #134 where instructed to not use the layer as parameter is not a good enough for us. 

We would for example like to add events when hovering over polygons in a specific layer or several different layers.

If we put the events "global" (with no layer/s) many events like mouseover are not triggering since it's only triggered when entering the main map. 

Also, for these global events the response is not the same as in the examples where events are used in the map component (without MapRef). And the data object with geometry coordinates is not included from what I can see.

Is this something that is planned to be address in the future and if not could it be?
Could this be achieved in another way while still using MapRef?

StackBlitz showing events not working : https://stackblitz.com/edit/react-fh3faw?file=src%2FMapController.tsx
(Need to add azure key in MapComponent)

**Comment by yulinscottkang** [comment]
hi @Morti, thanks for reporting the issue!

I couldn’t figure out how to get `mapRef.events.add` to work with a `layerRef`, but there's a workaround.

To add listeners to a layer, you may use `<AzureMapLayerProvider>` and set the `events` prop.
```js
<AzureMapLayerProvider type="SymbolLayer"
  events={{
    click: (e: any) => { console.log("onClick", e); },
    mouseover: (e: any) => { console.log("onMouseover", e); }
  }}
/>
```

Full example:
```js
import React, { useContext, useEffect } from "react";
import {
  AzureMap,
  AzureMapsContext,
  AzureMapDataSourceContext,
  AzureMapDataSourceProvider,
  AzureMapLayerProvider,
  AzureMapsProvider,
  IAzureMapDataSourceProps,
  IAzureMapsContextProps,
  IAzureMapOptions,
} from "react-azure-maps";
import { AuthenticationType, data } from "azure-maps-control";

const option: IAzureMapOptions = {
  authOptions: {
    authType: AuthenticationType.subscriptionKey,
    subscriptionKey: "", // Your subscription key
  },
};

const generateRandomPoints = (cnt: number) => {
  var layerData = [];
  for (var i = 0; i < cnt; i++) {
    layerData.push(
      new data.Feature(
        new data.Point([Math.random() * 360 - 180, Math.random() * 170 - 85]),
        {
          title: "Pin_" + i,
        }
      )
    );
  }
  return layerData;
}

const MapController = () => {
  const { isMapReady } = useContext<IAzureMapsContextProps>(AzureMapsContext);
  const { dataSourceRef } = useContext<IAzureMapDataSourceProps>(AzureMapDataSourceContext);

  useEffect(() => {
    if (isMapReady && dataSourceRef) {
      // @ts-ignore
      dataSourceRef.add(generateRandomPoints(100));
    }
  }, [isMapReady, dataSourceRef]);

  return null;
};

const Map: React.FC = () => {
  return (
    <div style={{ height: "600px" }}>
      <AzureMapsProvider>
        <AzureMap options={option}>
          <AzureMapDataSourceProvider id={"test"}>
            <AzureMapLayerProvider
              type="SymbolLayer"
              events={{
                click: (e: any) => {
                  console.log("onClick", e);
                },
                mouseover: (e: any) => {
                  console.log("onMouseover", e);
                },
              }}
            />
            <MapController />
          </AzureMapDataSourceProvider>
        </AzureMap>
      </AzureMapsProvider>
    </div>
  );
};

export default Map;

```

**Comment by Morti** [comment]
Thanks for the response, would be nice if it would be possible to get the `mapRef.event.add ` to work in the future. 

I'll do some testing with the workaround you posted and see if it will be enough for now
