### ISSUE TITLE
Getting error while using react-azure-maps - TypeError: window.URL.createObjectURL is not a function

### ISSUE THREAD

**Issue by Ut1998** [Azure/react-azure-maps#168]
I am trying to use react-azure-maps but it is throwing error - TypeError: window.URL.createObjectURL is not a function
Can you please help me what is the issue with this.

"react-azure-maps": "^0.4.8" - This is the version I am using

**Comment by yulinscottkang** [comment]
Are you running it in a server/node.js environment or within a browser? It's worth noting that the Azure Maps WebSDK is designed for client-side use. So, if you intend to use it in a server-side rendering scenario, you'll need to consider some form of lazy loading. For example, https://github.com/yulinscottkang/nextjs-azure-maps.
