### ISSUE TITLE
Custom Styling for Region Color Change at Zoom Level 2

### ISSUE THREAD

**Issue by sangeetha321** [Azure/react-azure-maps#171]
Hello Team,
We are currently working on implementing a Dashboard map view using react-azure-maps, but we have encountered a challenge in achieving our desired result.
Specifically, we need to change the color of regions from white to green while keeping the ocean color as its default blue.

In **Azure Maps**, **zoom level 2 and the 'road' style** provide one result, whereas in the **react-azure-maps library, at zoom level 2 with the 'road' style**, we get a different view.

 Azure Maps view, [ zoom level :2, style:road]
![image](https://github.com/Azure/react-azure-maps-playground/assets/14287834/45eafaa4-530a-4c2e-9307-235987f3b847)

View provided by react-azure-maps package [ zoom level :2, style:road]
![image](https://github.com/Azure/react-azure-maps-playground/assets/14287834/5e2d01c1-f8f5-4e70-861c-904fae1c2b69)

However, when we increase the zoom level to 4, some regions of the map are green in color. 
![image](https://github.com/Azure/react-azure-maps-playground/assets/14287834/feb782d4-77b6-4bf0-84b6-9bcf40226aa1)

As we've explored the available options within the react-azure-maps library, we haven't found a straightforward way to customize the styling to meet this requirement.

Could you please advise us on how we can achieve this specific styling change within the react-azure-maps library at a zoom level of 2?

Thank you in advance for your help, and we look forward to your response

**Comment by dubiety** [comment]
@sangeetha321 , can you try our `v1.0.0-beta.3` version? You should be able to see consistent map style.

**Comment by sangeetha321** [comment]
> @sangeetha321 , can you try our [`v1.0.0-beta.3` version](https://www.npmjs.com/package/react-azure-maps/v/1.0.0-beta.3)? You should be able to see consistent map style. We'll release our formal `v1.0.0` soon in case you want to use it on production site.
> 
> I'll close this issue, if it doesn't work for you, feel free to re-open this issue. Thank you very much.

Thank you for the update!
I'll definitely give the v1.0.0-beta.3 version a try to check out the map style.
We'll look forward to having the formal v1.0.0 version on our production site. Thanks again for your assistance
