### ISSUE TITLE
getting mapContext for AzureMapFeature

### ISSUE THREAD

**Issue by sangeetha321** [Azure/react-azure-maps#172]
Hello team, 
I have several polygons on the map, and I want to zoom to a specific polygon when a button is clicked. How can I obtain the bounds of that polygon to use it with setCamera?
```
const polygon = mapContext
          .getPolygonFeatures()
          .find(p => p.getProperties().zoneId === zoneId)

        bounds = polygon.getBounds()
        map.setCamera({
          bounds,
        })
```
How to get the above **mapContext** in the below component?

```
<AzureMapDataSourceProvider
      id={'GeoZonePolygonPolygonLayerProvider'}
      options={{}}
    >
 <AzureMapLayerProvider
        id={'GeoZonePolygonPolygonLayer'}
        type={'PolygonLayer'}
        options={{
          fillColor: 'yellow}}  />`
        `<AzureMapLayerProvider
        id={'polygonExample2 LayerProvider'}
        type={'LineLayer'}
        options={{ strokeColor: 'red}}
      />
      
     {
       polygonZones.map((zone: any) => {
          const rendId = Math.random().toString()
          const coordinates = zone.coordinates 
            
          return (
            <AzureMapFeature
              id={rendId}
              type="Polygon"
              coordinates={[coordinates]}
              properties={{
                zoneId: zone.zoneId,
                color: getZoneColor(zone),
              }}
            />
          )
        }) as any
      }
    </AzureMapDataSourceProvider>
```

**Comment by yulinscottkang** [comment]
I'm a bit uncertain about what exactly `mapContext` refers to in this code snippet. Additionally, I couldn't find any functions like `getPolygonFeatures` in azure-maps-control or react-azure-maps. If you're looking to obtain a reference to the map object, you can achieve that through the `<AzureMapsContext>` context. See example here: https://github.com/Azure/react-azure-maps-playground/blob/master/src/examples/MapRef/MapController.tsx

**Comment by sangeetha321** [comment]
> I'm a bit uncertain about what exactly `mapContext` refers to in this code snippet. Additionally, I couldn't find any functions like `getPolygonFeatures` in azure-maps-control or react-azure-maps. If you're looking to obtain a reference to the map object, you can achieve that through the `<AzureMapsContext>` context. See example here: https://github.com/Azure/react-azure-maps-playground/blob/master/src/examples/MapRef/MapController.tsx

My requirement is to get the coodinates of a particular polygon on a button click. You can leave the method `getPolygonFeatures`, it is a built in method,  `getPolygonFeatures`, but if you look into it, that gives us the option to get the `bounds`

**Comment by yulinscottkang** [comment]
To get render features, you may want to take a look at the `getRenderedShapes` function from [SourceManager ](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.sourcemanager?view=azure-maps-typescript-latest#azure-maps-control-atlas-sourcemanager-getrenderedshapes)and [LayerManager](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.layermanager?view=azure-maps-typescript-latest#azure-maps-control-atlas-layermanager-getrenderedshapes).
