### ISSUE TITLE
Is thre a reason for removing the dependency @testing-library/react-hooks in version 1.0.0

### ISSUE THREAD

**Issue by sangeetha321** [Azure/react-azure-maps#180]
Is there a reason for removing the dependency "@testing-library/react-hooks" in version 1.0.0? 

After migrating to version 1.0.0, we noticed that this dependency has been removed.  We were using this dependency in our application.

react-azure-maps@0.1.4:
  version "0.1.4"
  resolved "https://registry.yarnpkg.com/react-azure-maps/-/react-azure-maps-0.1.4.tgz#828f17f09fc74ce11d722a9515e05a2401872829"
  integrity sha512-bMkh0p5wASncbvsMO2fCc3XwL5T1b9gV0sRn4WCtd9qweOFaJWxXfwlIE2L8YSj2BjbU2WZaZye+yhcmhsqKgg==
  dependencies:
    **"@testing-library/react-hooks" "^3.2.1"**
    "@types/uuid" "^7.0.0"
    azure-maps-control "2.0.31"
    guid-typescript "^1.0.9"
    mapbox-gl "^1.10.0"
    react-test-renderer "^16.13.0"
    rollup-plugin-peer-deps-external "^2.2.2"
    rollup-plugin-postcss "^2.1.1"

**Comment by yulinscottkang** [comment]
[@testing-library/react-hooks](https://www.npmjs.com/package/@testing-library/react-hooks) has been replaced with [@testing-library/react](https://www.npmjs.com/package/@testing-library/react) as part of React 18 migration. ([Ref](https://github.com/testing-library/react-testing-library/pull/991)). 

To use either testing libraries, you should install the package to your application's `devDependencies`, and not reply on dependecies from react-azure-maps.
