### ISSUE TITLE
Popup content is non-interactive (react components are rendered as static markup in Popup content)

### ISSUE THREAD

**Issue by rdo-mgowland** [Azure/react-azure-maps#182]
I have buttons that display in my popups that I need the user to be able to click.
I believe the click  events on the buttons within a popup are not working becuase when rendering the popup content you are using renderToStaticMarkup. 

I think useCreateAzureMapPopup should be changed from this:

```
const [popupRef] = useState<atlas.Popup>(
    new atlas.Popup({ ...options, content: renderToStaticMarkup(popupContent) })
  )
```

To actually render the react component so it can have interactive content.

**Comment by rdo-mgowland** [comment]
As a workaround
```
return(
<AzureMap>
    <AzureMapPopup isVisible={!!myPopupData} options={popupOptions} popupContent={<div id="my-popup-container" />} />
    {(() => {
    const d = document.getElementById("my-popup-container");
    if (d && myPopup) {
        return React.createPortal(<MyCustomPopup properties={myPopupData} />, d);
    }
    return <></>;
    })()}
</AzureMap>
)
```

**Comment by yulinscottkang** [comment]
One possible approach would be to create a custom Popup component, similar to `<AzureMapPopup>`, and utilize ReactDOM.render to generate the content for the popup. That'll probably be more flexible for your use case.

You'll need to use the `<AzureMapsContext>` from react-azure-maps to get a `mapRef` reference, and create an instance of atlas.Popup that you can attach to the map by calling `popup.open(mapRef)`. Similar to what [useCreateAzureMapPopup.ts ](https://github.com/Azure/react-azure-maps/blob/3b7f5f667c5bed8e82a7e59a8afa660969b8d936/src/components/AzureMapPopup/useCreateAzureMapPopup.ts#L4)does now.

I believe @adityagupta-msft has implemented something similar, so maybe he can also provide a code snippet.

**Comment by rdo-mgowland** [comment]
Could we get this added to this library? Surely a lot of people would want this functionality.

**Comment by adityagupta-msft** [comment]
Hi @rdo-mgowland, sorry I missed this. The solution I came up with is the following: 

```
import { useContext, useEffect, memo, useState } from "react";
import ReactDOM from "react-dom";
import atlas from "azure-maps-control";
import {
  IAzureMapsContextProps,
  MapType,
  IAzureMapPopup,
} from "react-azure-maps/dist/types/types";
import { AzureMapsContext } from "react-azure-maps";

export const GeoMapPopup = memo(
  ({ isVisible, popupContent, options, events }: IAzureMapPopup) => {
    const { mapRef } = useContext<IAzureMapsContextProps>(AzureMapsContext);
    const popupRef = useCreatePopup({ options, popupContent, isVisible });

    useCheckRefMount<MapType, boolean>(mapRef, true, (mref) => {
      events &&
        events.forEach(({ eventName, callback }) => {
          mref.events.add(eventName, popupRef, callback);
        });
      return () => {
        mref.popups.remove(popupRef);
      };
    });

    useEffect(() => {
      if (mapRef) {
        if (isVisible && !popupRef.isOpen()) {
          popupRef.open(mapRef);
        } else if (
          mapRef.popups.getPopups().length &&
          !isVisible &&
          popupRef.isOpen()
        ) {
          popupRef.close();
        }
      }
    }, [isVisible]);

    return null;
  }
);

const useCreatePopup = ({
  options,
  popupContent,
  isVisible,
}: Pick<IAzureMapPopup, "popupContent" | "options" | "isVisible">) => {
  const containerRef = document.createElement("div");
  ReactDOM.render(popupContent, containerRef);

  const [popupRef] = useState<atlas.Popup>(
    new atlas.Popup({ ...options, content: containerRef })
  );
  const { mapRef } = useContext<IAzureMapsContextProps>(AzureMapsContext);

  useEffect(() => {
    const containerRef = document.createElement("div");
    ReactDOM.render(popupContent, containerRef);
    popupRef.setOptions({
      ...options,
      content: containerRef,
    });
    if (mapRef && isVisible && !popupRef.isOpen()) {
      popupRef.open(mapRef);
    }
  }, [options, popupContent]);

  return popupRef;
};

function useCheckRefMount<T, T1>(
  dep: T | null,
  on: T1 | null,
  callback: (dep: T, on: T1) => void
) {
  useEffect(() => {
    if (dep && on) {
      return callback(dep, on);
    }
  }, []);
}
```
It takes functionality from useCreateAzureMapPopup.ts and I created a new popup component called GeoMapPopup which can be used. 

I am not sure about the efficiency of the solution as it requires creating a new DOM element every time but I hope it helps!

**Comment by yulinscottkang** [comment]
See @adityagupta-msft's comment for a working solution.

**Comment by yulinscottkang** [comment]
Playground example by @Chia-Chi-Shen 
https://azure.github.io/react-azure-maps-playground/?path=/docs/map-annotations-interactive-popup--docs
