### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by atulsh1983** [Azure/react-azure-maps#185]
Have installed azure-maps-control  npm package

This run perfectly on my localhost, but when same code deployed on prod

it gives error:

Uncaught ReferenceError: b is not defined

error in blob files JS

**Comment by yulinscottkang** [comment]
Without seeing your specific code and the context in which the error occurs, it's challenging to provide a more specific solution.

Make sure that you have bundled all the dependencies packages correctly in your production code. Check if there are any environmental differences that might be causing the error.

Use browser development tools to inspect the error in the production environment. This can help to pinpoint the exact location and what is undefined.

**Comment by savi-react** [comment]
> Have installed azure-maps-control npm package
> 
> This run perfectly on my localhost, but when same code deployed on prod
> 
> it gives error:
> 
> Uncaught ReferenceError: b is not defined
> 
> error in blob files JS
same issue facing
![issue](https://github.com/Azure/react-azure-maps/assets/138099244/c866f8a9-58ea-4043-8399-7f2760bfdca9)

**Comment by yulinscottkang** [comment]
`azure-maps-control@3.0.3` now includes native support for ESM, which works more seamlessly with bundlers and minifiers. You might want to give it a try and see if it makes any difference.

**Comment by sunallam** [comment]
Hi @yulinscottkang ,
Do we have any work around for this i am also facing the same issue.
Updated the dependency with mentioned version but no luck on this

"azure-maps-control": "^3.0.3",
"react-azure-maps": "^1.0.0",
"react": "^18.2.0",
"react-router-dom": "^6.17.0",
"react-scripts": "^5.0.1",

The above are the dependency versions that i have
Thanks

**Comment by yulinscottkang** [comment]
@sunallam, can you let me know which minifier is being used and share the configurations for the minifier?

**Comment by alvaradojl** [comment]
I have the same issue with version  "azure-maps-control": "^3.1.2",
as @sunallam I'm using create-react-app.
@yulinscottkang do you know any workaround?

**Comment by yulinscottkang** [comment]
See https://github.com/Azure/react-azure-maps/issues/193#issuecomment-2046350108 for solution.
