### ISSUE TITLE
azure map not loading in production with subscription key 

### ISSUE THREAD

**Issue by savi-react** [Azure/react-azure-maps#186]

**Comment by yulinscottkang** [comment]
To assist in identifying the problem, please provide a code snippet that can reproduce this issue. It would be helpful if you can also include the http status code and the response body of the failing APIs.

**Comment by savi-react** [comment]
getting these error while deploying to production 
![isue](https://github.com/Azure/react-azure-maps/assets/138099244/42cac7a7-b3ef-4bac-bdd1-02b1ce103080)

**Comment by yulinscottkang** [comment]
Can you click on the line number and show what `v` is? Also, based on the warning, it seems that you're referencing atlas.min.js separately. It should also be bundled with your JS files.

**Comment by ashishkabuni** [comment]
I am also facing same issue not sure why we are getting this issue on live environment. In local it is working properly. 

<img width="489" alt="image" src="https://github.com/Azure/react-azure-maps/assets/146758759/2e2c79f6-0150-4a64-a4df-dcc2773e5938">
<img width="999" alt="image" src="https://github.com/Azure/react-azure-maps/assets/146758759/061d8eaf-ac96-4c18-8327-bc1984678e29">

**Comment by Joxterian** [comment]
Hello, I'm using `react-azure-maps@1.0.0` and `azure-maps-control@3.0.3` and have this error: 
![image](https://github.com/Azure/react-azure-maps/assets/50087230/2f83d226-f37d-42e3-9067-11e74caf248d)
![image](https://github.com/Azure/react-azure-maps/assets/50087230/f33171f1-d789-40da-976b-6778127847fd)

Using the react-scripts command it works perfectly: 
![image](https://github.com/Azure/react-azure-maps/assets/50087230/9baef041-d7d7-47a7-afe8-ee6b7ef80e55)

But once it's compiled and deployed in the server I get the previous errors and the map, appears but empty: 
![image](https://github.com/Azure/react-azure-maps/assets/50087230/0c1e6c96-0d80-406d-8fbb-35fc5ecabf3c)

**Comment by yulinscottkang** [comment]
@ashishkabuni, @Joxterian, can you let me know which minifier is being used and share the configurations for the minifier?

**Comment by alvaradojl** [comment]
Seems the same issue as #185

**Comment by yulinscottkang** [comment]
See https://github.com/Azure/react-azure-maps/issues/193#issuecomment-2046350108 for solution.
