### ISSUE TITLE
Azure Map not loading correct in prod

### ISSUE THREAD

**Issue by jimmyrleung** [Azure/react-azure-maps#187]
I'm working with Azure Maps in a nextjs application and implemented according to that example: https://react-azure-maps.vercel.app/live-example-map

It works fine in dev, but I'm receiving the following error for the app deployed:
![image](https://github.com/Azure/react-azure-maps/assets/22828137/6b32d751-5711-4826-9f19-1175668c064c)

When clicking in the UUID, it shows this piece of code:
![image](https://github.com/Azure/react-azure-maps/assets/22828137/e32abc22-5d5c-4645-9e58-d9eabeb78308)

In terms of the UI, the difference is: 

Local - working fine
![image](https://github.com/Azure/react-azure-maps/assets/22828137/50a32528-a9a5-479d-a0a5-72160ded3d58)

Deployed - broken
![image](https://github.com/Azure/react-azure-maps/assets/22828137/f8ea0a92-7b28-4b6b-8e88-ef972f0191b0)

And the difference is not only the map not loading, it is also not interactive

**Comment by yulinscottkang** [comment]
Which versions are currently in use? You might also want to check out this [example](https://github.com/yulinscottkang/nextjs-azure-maps), which includes next@14.0.3, react-azure-maps@1.0.0, and azure-maps-control@3.0.2. I've tested production deployment using `next build` and `next start`, and no issues were observed.

**Comment by jimmyrleung** [comment]
Hey @yulinscottkang here we're using next@13.5.4, azure-maps-control@3.0.2, and react-azure-maps@1.0.0, but I think I have found the issue by comparing our config with the example you shared, and it is related to the `swcMinify` config.

The error occurs when swcMinify is set to false:
![image](https://github.com/Azure/react-azure-maps/assets/22828137/b912898c-8d7b-4adf-9fe2-71f4551434ca)

And it does work when we have swcMinify set to true:
![image](https://github.com/Azure/react-azure-maps/assets/22828137/805279d7-0f84-45f1-a200-18ee10a6be10)

Would you know of any options we could update to test and see if we could get that to work with `swcMinify: false` ? I'm asking because we had to disable that option to fix some other issues we had in our app, so if we could keep it like that, that would be the best option for us

**Comment by yulinscottkang** [comment]
Based on the Next.js documentation, terser is used when swcMinify is set to false. You might want to experiment with different terser options to see if it makes a difference. Unfortunately, Next.js doesn't directly support passing terser options, so you'll likely need a [workaround](https://github.com/vercel/next.js/discussions/24275). Disabling minification altogether for production builds is another option, but it's probably not the ideal route to take.

**Comment by jimmyrleung** [comment]
Yeah we just noticed that, and we also noticed that swcMinify option will be removed in Next.js 15 as SWC will be enabled by default, so we'll probably go with the option of setting swcMinify to true and handle any other app errors we find. Thanks for your support @yulinscottkang

**Comment by DPid-ETI** [comment]
@yulinscottkang,
I am having this exact problem, but I am not using next.js, just react 17. We have this issue on different apps with different build options. both are react. How can I fix this problem? 

react 17
"azure-maps-control": "^3.5.0",
"react-azure-maps": "^1.0.0",
