### ISSUE TITLE
IAzureMapLayerType and SymbolLayerOptions not found

### ISSUE THREAD

**Issue by gmjcbs** [Azure/react-azure-maps#191]
Hi,
I am getting not found error for IAzureMapLayerType and SymbolLayerOptions while implementing MarkersExample.

![image](https://github.com/Azure/react-azure-maps/assets/136578726/d91c8db2-8c82-41de-bfad-f0e36fe6f4cb)

packages installed:
"azure-maps-control": "^3.0.1",
"react-azure-maps": "^1.0.0"

Any thoughts around it...

Thanks in advance.. :)

**Comment by yulinscottkang** [comment]
It looks like you're importing TypeScript interfaces or types in a JavaScript file. Try renaming your App.js to App.ts.
