### ISSUE TITLE
Custom cluster

### ISSUE THREAD

**Issue by gmjcbs** [Azure/react-azure-maps#202]
Hi,

Thank you for your help on previous queries.

Currently I am putting markers to clusters which is working fine.
But I want cluster color to be same as maximum number of marker's color. For example, if a cluster has 5 red markers and 2 blue markers, then cluster color should be red.

I tried few things however it does not work.
It would be of great help if you can suggest something.

sample code:

import {
  AzureMap,
  AzureMapDataSourceProvider,
  AzureMapFeature,
  AzureMapLayerProvider,
  AzureMapsProvider,
  AzureMapsContext,
} from "react-azure-maps";
import { AuthenticationType, data } from "azure-maps-control";
import "azure-maps-control/dist/atlas.min.css";
import React, { useMemo, useState, useContext } from "react";
import { Button } from "@mui/material";
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';

const CameraController = ({ longitude, latitude }) => {
  const { mapRef, isMapReady } = useContext(AzureMapsContext);
  if (mapRef && isMapReady) {
    mapRef.setCamera({ center: [longitude, latitude], zoom: 12 });
  }
  return null;
};

export default function App() {
  const [markers, setMarkers] = useState([
    {
      "area_description": "B40 at DeLa",
      "consumption_diff": -6620.51,
      "latitude": 36.998577,
      "longitude": -122.007392
    },
    {
      "area_description": "B40 at DeLa",
      "consumption_diff": -6620.51,
      "latitude": 36.998726,
      "longitude": -122.005175
    },
    {
      "area_description": "B40 at end",
      "consumption_diff": -6814.88,
      "latitude": 37.031931,
      "longitude": -121.987327
    },
    {
      "area_description": "B40 at end",
      "consumption_diff": -6814.88,
      "latitude": 37.032057,
      "longitude": -121.987473
    },
    {
      "area_description": "Deer Path Rd.",
      "consumption_diff": -2854.32,
      "latitude": 37.00692,
      "longitude": -122.032829
    },
    {
      "area_description": "El Rancho",
      "consumption_diff": 858.96,
      "latitude": 37.011864,
      "longitude": -122.021117
    },
    {
      "area_description": "El Rancho",
      "consumption_diff": 858.96,
      "latitude": 37.012282,
      "longitude": -122.021585
    },
    {
      "area_description": "GH Rd-Near Westwood",
      "consumption_diff": 443.78,
      "latitude": 37.002297,
      "longitude": -122.032153
    },
    {
      "area_description": "GH Rd-Near Westwood",
      "consumption_diff": 443.78,
      "latitude": 37.002758,
      "longitude": -122.032169
    },
    {
      "area_description": "Hidden Creek Ln.",
      "consumption_diff": 277.37,
      "latitude": 37.004673,
      "longitude": -122.032575
    },
    {
      "area_description": "Hidden Creek Ln.",
      "consumption_diff": 277.37,
      "latitude": 37.005448,
      "longitude": -122.033
    },
    {
      "area_description": "Mosswood Dr.",
      "consumption_diff": 7656.07,
      "latitude": 37.002763,
      "longitude": -122.033904
    },
    {
      "area_description": "Mosswood Dr.",
      "consumption_diff": 7656.07,
      "latitude": 37.002725,
      "longitude": -122.033953
    },
    {
      "area_description": "Mosswood Dr.",
      "consumption_diff": 7656.07,
      "latitude": 37.002677,
      "longitude": -122.03402
    },
    {
      "area_description": "Mosswood Dr.",
      "consumption_diff": 7656.07,
      "latitude": 37.002522,
      "longitude": -122.033132
    },
    {
      "area_description": "Ridge Rd.",
      "consumption_diff": 1957.23,
      "latitude": 37.002996,
      "longitude": -122.031476
    },
    {
      "area_description": "Ridge Rd.",
      "consumption_diff": 1957.23,
      "latitude": 37.002648,
      "longitude": -122.031219
    },
    {
      "area_description": "Tanner Heights",
      "consumption_diff": -9568.47,
      "latitude": 36.990507,
      "longitude": -122.025663
    },
    {
      "area_description": "Tanner Heights",
      "consumption_diff": -9568.47,
      "latitude": 36.990469,
      "longitude": -122.025557
    },
    {
      "area_description": "Tanner Heights",
      "consumption_diff": -9568.47,
      "latitude": 36.990676,
      "longitude": -122.025645
    },
    
  ]);

  const mapOption = {
    authOptions: {
      authType: AuthenticationType.subscriptionKey,
      subscriptionKey: '', // Your subscription key
    },
  };

  let consumptionDiffColorCounts = {
    positive: 0,
    negative: 0
  };

  const renderPoint = (marker) => {
    const rendId = Math.random();
    let point = new data.Position(marker.longitude, marker.latitude);
    if (marker.consumption_diff > 0) {
      consumptionDiffColorCounts.positive++;
    } else {
      consumptionDiffColorCounts.negative++;
    }

    return (
      <AzureMapFeature
        key={rendId}
        id={rendId.toString()}
        type="Point"
        coordinate={point}
        properties={{
          title: marker.consumption_diff,
          icon: marker.consumption_diff<0?'marker-blue':'marker-red',
        }}
      />
    );
  };

  const memoizedMarkerRender = useMemo(
    () => markers && markers.map((marker) => renderPoint(marker)),
    [markers]
  );

  const bubbleLayerOptions = {
    //Scale the size of the clustered bubble based on the number of points inthe cluster.
    radius: [
      'step',
      ['get', 'point_count'],
      15, //Default of 10 pixel radius.
      10,15, 
    ],

    //Change the color of the cluster based on the value on the point_cluster property of the cluster.
    color: [
      'match',
      ['get', 'consumption_diff'], // Check the actual consumption_diff value
      'positive', 'blue', // Positive value gets blue
      'negative', 'red',  // Negative value gets red
      'gray'               // Default color for other cases
    ],
    strokeWidth: 0,
    filter: ['has', 'point_count'], //Only rendered data points which have a point_count property, which clusters do.

  };

  return (
    <Card style={{ height: '650px' }}>
      <CardContent>
        <div style={{ height: '650px' }}>
          <AzureMapsProvider>
            <AzureMap options={mapOption}>
              <AzureMapDataSourceProvider id={"DataSource"} options={{
                //Tell the data source to cluster point data.
                cluster: true
              }}>
                <AzureMapLayerProvider
                  id={'clusters LayerProvider'}
                  options={bubbleLayerOptions}
                  type="BubbleLayer"
                ></AzureMapLayerProvider>
                <AzureMapLayerProvider
                  id={'BubbleLayer2 LayerProvider'}
                  options={{
                    iconOptions: {
                      image: 'none', //Hide the icon image.
                    },
                    textOptions: {
                      textField: ['get', 'point_count_abbreviated'],
                      offset: [0, 0.4],
                    },
                  }}
                  type="SymbolLayer"
                ></AzureMapLayerProvider>
                <AzureMapLayerProvider
                  id={'BubbleLayer2 LayerProvider'}
                  options={{
                    iconOptions: {
                      image: 'none', //Hide the icon image.
                    },
                    textOptions: {
                      textField: ['get', 'point_count_abbreviated'],
                      offset: [0, 0.4],
                    },
                  }}
                  type="SymbolLayer"
                ></AzureMapLayerProvider>
                <AzureMapLayerProvider
                  id={'markers AzureMapLayerProvider'}
                  options={{
                    textOptions: {
                      color: '#000000',
                      size: 16,
                      textField: ['get', 'title'], //Specify the property name that contains the text you want to appear with the symbol.
                      offset: [0, 1.2]
                    },
                    iconOptions: {
                      image: ['get', 'icon']
                    },
                    filter: ['!', ['has', 'point_count']]
                  }}
                  type={'SymbolLayer'}
                />
                {memoizedMarkerRender}
                <CameraController
                  latitude={markers[0].latitude}
                  longitude={markers[0].longitude}
                />
              </AzureMapDataSourceProvider>
            </AzureMap>
          </AzureMapsProvider>
        </div>

      </CardContent>
    </Card>
  );
}

**Comment by yulinscottkang** [comment]
You may use `clusterProperties` to define custom properties for the cluster, for example adding a `sum`:
```js
<AzureMapDataSourceProvider
  id={"DataSource"}
  options={{
    //Tell the data source to cluster point data.
    cluster: true,
    //Defines custom properties for the cluster
    clusterProperties: {
      sum: ["+", ["get", "consumption_diff"]],
    },
  }}
>
```

Don't forget to add `consumption_diff` to the feature properties as well.
```js
<AzureMapFeature
  key={rendId}
  id={rendId.toString()}
   type="Point"
  coordinate={point}
  properties={{
    consumption_diff: marker.consumption_diff,
    title: marker.consumption_diff,
    icon: marker.consumption_diff < 0 ? "marker-blue" : "marker-red",
  }}
/>
```

And you can use the custom defined `sum` property like:
```js
const bubbleLayerOptions = {
    ...
    //Change the color of the cluster based on the value on the point_cluster property of the cluster.
    color: ["step", ["get", "sum"], "blue", 0, "red"],
    strokeWidth: 0,
    filter: ["has", "point_count"], //Only rendered data points which have a point_count property, which clusters do.
};
```

Here's the full example:
```js
import {
  AzureMap,
  AzureMapDataSourceProvider,
  AzureMapFeature,
  AzureMapLayerProvider,
  AzureMapsProvider,
  AzureMapsContext,
} from "react-azure-maps";
import { AuthenticationType, data } from "azure-maps-control";
import "azure-maps-control/dist/atlas.min.css";
import React, { useMemo, useState, useContext } from "react";

const CameraController = ({ longitude, latitude }) => {
  const { mapRef, isMapReady } = useContext(AzureMapsContext);
  if (mapRef && isMapReady) {
    mapRef.setCamera({ center: [longitude, latitude], zoom: 12 });
  }
  return null;
};

export default function App() {
  const [markers, setMarkers] = useState([
    {
      area_description: "B40 at DeLa",
      consumption_diff: -6620.51,
      latitude: 36.998577,
      longitude: -122.007392,
    },
    {
      area_description: "B40 at DeLa",
      consumption_diff: -6620.51,
      latitude: 36.998726,
      longitude: -122.005175,
    },
    {
      area_description: "B40 at end",
      consumption_diff: -6814.88,
      latitude: 37.031931,
      longitude: -121.987327,
    },
    {
      area_description: "B40 at end",
      consumption_diff: -6814.88,
      latitude: 37.032057,
      longitude: -121.987473,
    },
    {
      area_description: "Deer Path Rd.",
      consumption_diff: -2854.32,
      latitude: 37.00692,
      longitude: -122.032829,
    },
    {
      area_description: "El Rancho",
      consumption_diff: 858.96,
      latitude: 37.011864,
      longitude: -122.021117,
    },
    {
      area_description: "El Rancho",
      consumption_diff: 858.96,
      latitude: 37.012282,
      longitude: -122.021585,
    },
    {
      area_description: "GH Rd-Near Westwood",
      consumption_diff: 443.78,
      latitude: 37.002297,
      longitude: -122.032153,
    },
    {
      area_description: "GH Rd-Near Westwood",
      consumption_diff: 443.78,
      latitude: 37.002758,
      longitude: -122.032169,
    },
    {
      area_description: "Hidden Creek Ln.",
      consumption_diff: 277.37,
      latitude: 37.004673,
      longitude: -122.032575,
    },
    {
      area_description: "Hidden Creek Ln.",
      consumption_diff: 277.37,
      latitude: 37.005448,
      longitude: -122.033,
    },
    {
      area_description: "Mosswood Dr.",
      consumption_diff: 7656.07,
      latitude: 37.002763,
      longitude: -122.033904,
    },
    {
      area_description: "Mosswood Dr.",
      consumption_diff: 7656.07,
      latitude: 37.002725,
      longitude: -122.033953,
    },
    {
      area_description: "Mosswood Dr.",
      consumption_diff: 7656.07,
      latitude: 37.002677,
      longitude: -122.03402,
    },
    {
      area_description: "Mosswood Dr.",
      consumption_diff: 7656.07,
      latitude: 37.002522,
      longitude: -122.033132,
    },
    {
      area_description: "Ridge Rd.",
      consumption_diff: 1957.23,
      latitude: 37.002996,
      longitude: -122.031476,
    },
    {
      area_description: "Ridge Rd.",
      consumption_diff: 1957.23,
      latitude: 37.002648,
      longitude: -122.031219,
    },
    {
      area_description: "Tanner Heights",
      consumption_diff: -9568.47,
      latitude: 36.990507,
      longitude: -122.025663,
    },
    {
      area_description: "Tanner Heights",
      consumption_diff: -9568.47,
      latitude: 36.990469,
      longitude: -122.025557,
    },
    {
      area_description: "Tanner Heights",
      consumption_diff: -9568.47,
      latitude: 36.990676,
      longitude: -122.025645,
    },
  ]);

  const mapOption = {
    authOptions: {
      authType: AuthenticationType.subscriptionKey,
      subscriptionKey: "", // Your subscription key
    },
  };

  let consumptionDiffColorCounts = {
    positive: 0,
    negative: 0,
  };

  const renderPoint = (marker) => {
    const rendId = Math.random();
    let point = new data.Position(marker.longitude, marker.latitude);
    if (marker.consumption_diff > 0) {
      consumptionDiffColorCounts.positive++;
    } else {
      consumptionDiffColorCounts.negative++;
    }

    return (
      <AzureMapFeature
        key={rendId}
        id={rendId.toString()}
        type="Point"
        coordinate={point}
        properties={{
          consumption_diff: marker.consumption_diff,
          title: marker.consumption_diff,
          icon: marker.consumption_diff < 0 ? "marker-blue" : "marker-red",
        }}
      />
    );
  };

  const memoizedMarkerRender = useMemo(
    () => markers && markers.map((marker) => renderPoint(marker)),
    [markers]
  );

  const bubbleLayerOptions = {
    //Scale the size of the clustered bubble based on the number of points inthe cluster.
    radius: [
      "step",
      ["get", "point_count"],
      15, //Default of 10 pixel radius.
      10,
      15,
    ],

    //Change the color of the cluster based on the value on the point_cluster property of the cluster.
    color: ["step", ["get", "sum"], "blue", 0, "red"],
    strokeWidth: 0,
    filter: ["has", "point_count"], //Only rendered data points which have a point_count property, which clusters do.
  };

  return (
    <div style={{ height: "650px" }}>
      <AzureMapsProvider>
        <AzureMap options={mapOption}>
          <AzureMapDataSourceProvider
            id={"DataSource"}
            options={{
              //Tell the data source to cluster point data.
              cluster: true,
              //Defines custom properties for the cluster
              clusterProperties: {
                sum: ["+", ["get", "consumption_diff"]],
              },
            }}
          >
            <AzureMapLayerProvider
              id={"clusters LayerProvider"}
              options={bubbleLayerOptions}
              type="BubbleLayer"
            ></AzureMapLayerProvider>
            <AzureMapLayerProvider
              id={"BubbleLayer2 LayerProvider"}
              options={{
                iconOptions: {
                  image: "none", //Hide the icon image.
                },
                textOptions: {
                  textField: ["get", "point_count_abbreviated"],
                  offset: [0, 0.4],
                },
              }}
              type="SymbolLayer"
            ></AzureMapLayerProvider>
            <AzureMapLayerProvider
              id={"BubbleLayer2 LayerProvider"}
              options={{
                iconOptions: {
                  image: "none", //Hide the icon image.
                },
                textOptions: {
                  textField: ["get", "point_count_abbreviated"],
                  offset: [0, 0.4],
                },
              }}
              type="SymbolLayer"
            ></AzureMapLayerProvider>
            <AzureMapLayerProvider
              id={"markers AzureMapLayerProvider"}
              options={{
                textOptions: {
                  color: "#000000",
                  size: 16,
                  textField: ["get", "title"], //Specify the property name that contains the text you want to appear with the symbol.
                  offset: [0, 1.2],
                },
                iconOptions: {
                  image: ["get", "icon"],
                },
                filter: ["!", ["has", "point_count"]],
              }}
              type={"SymbolLayer"}
            />
            {memoizedMarkerRender}
            <CameraController
              latitude={markers[0].latitude}
              longitude={markers[0].longitude}
            />
          </AzureMapDataSourceProvider>
        </AzureMap>
      </AzureMapsProvider>
    </div>
  );
}
```

![Screenshot 2024-05-24 100104](https://github.com/Azure/react-azure-maps/assets/953349/d7b7cb00-3f8a-4f46-b411-73e96046d416)

**Comment by gmjcbs** [comment]
Thank you @yulinscottkang
