### ISSUE TITLE
How to Make AzureMap Stretch to Fit Parent?

### ISSUE THREAD

**Issue by MaverickEdberg** [Azure/react-azure-maps#83]
Currently I have an AzureMap inside of a div that can be resized. The canvas within the AzureMap component unfortunately does not resize when the parent div is resized, resulting in an empty section of the parent div. Is there any way to get the AzureMap component to stretch to fit it's parent? Thanks!

PS - I've tried messing with the autoResize function but this apparently only hooks onto the window's size.

**Comment by psrednicki** [comment]
Add parent container for `<AzureMap>` component and specify styles.

const MapComponent: React.FC = () => {
  return (
    <div style={{ height: '300px' }}>
      <AzureMap options={option} />
    </div>
  );
};

**Comment by MaverickEdberg** [comment]
@psrednicki Adding style to the parent element does not cause the underlaying `canvas`  to resize unfortunately. I ended up doing something like this:

```js
const azureMaps = useAzureMaps();
const [resizeListener, sizes] = useResizeAware();

useEffect(() => {
    azureMaps.mapRef?.resize();
}, [sizes.width]) // eslint-disable-line react-hooks/exhaustive-deps

return (
    <div>
        {resizeListener}
        <AzureMap
            options={options}
            containerClassName={styles.container}
        />
    </div>
);
```

Is there a better way?

**Comment by msasinowski** [comment]
It will be probably better to use just and ResiseObserver for that we will maybe implement that kind of stuff inside the package so you can just use some prop to control that e.g  `fitParent`

**Comment by sangeetha321** [comment]
I had similar issue, this is how I solved it

```
 const { mapRef, isMapReady } = useContext<IAzureMapsContextProps>(
    AzureMapsContext
  )

  useEffect(() => {
    if (mapRef && isMapReady) {
      if (props.height && props.width) {
        mapRef.resize(props.height, props.width)
      }
      mapRef.resize()
    }
  }, [mapRef, isMapReady, props.height, props.width])


```

**Comment by yulinscottkang** [comment]
See @sangeetha321's comment for a working solution.
