### ISSUE TITLE
Is this repo dead? 

### ISSUE THREAD

**Issue by lcoursey** [Azure/react-azure-maps#99]
Been a long time now since any releases or changes. Anyone got a solid fork that's up to date and has all the PR'd fixes?

**Comment by kaseychakos** [comment]
Doesn't seem worth wasting much more time on. Documentation is horrible. Good luck.

**Comment by dubiety** [comment]
Hi @lcoursey  and @kaseychakos , sorry for the late reply. This repo hasn't been updated for few months due to shortage of resources. We have a plan to update this library this year including overhauling the documentation. Will keep you posted and sorry for the inconvenience.
